# required to get an OSX environment
language: objective-c

before_script:
  # set the JAVA_HOME which is not set by default for OSX Travis-CI workers
  - export "JAVA_HOME=`/usr/libexec/java_home`"

  # Get hold of ANT.
  - brew update
  - brew install ant

  # Adobe Flash Player for CLI
  - brew install caskroom/cask/brew-cask
  - brew tap caskroom/versions
  - brew cask install flash-player-debugger

  # Set env. variable used by FlexUnit
  - export FLASH_PLAYER_EXE="/Applications/Flash Player Debugger.app/Contents/MacOS/Flash Player Debugger"

  # Grab SDK
  - mkdir -p flex_sdk_4.15.0
  - wget -O flex_sdk.zip http://mirrors.gigenet.com/apache/flex/4.15.0/binaries/apache-flex-sdk-4.15.0-bin.zip
  - unzip -q flex_sdk.zip -d flex_sdk_4.15.0
  - mkdir -p flex_sdk_4.15.0/frameworks/libs/player/11.1/
  - mkdir -p flex_sdk_4.15.0/frameworks/libs/player/22.0/
  - wget -O playerglobal.swc http://fpdownload.macromedia.com/get/flashplayer/updaters/22/playerglobal22_0.swc

  # Init PlayerGlobals
  - echo env.PLAYERGLOBAL_HOME=libs/player > flex_sdk_4.15.0/env.properties

  # Need to put playerglobal to 11.1 folder, because flex-config.xml will take player global from 11.1 folder.
  # Little bit hackish :)
  - cp -f playerglobal.swc flex_sdk_4.15.0/frameworks/libs/player/11.1/
  - cp -f playerglobal.swc flex_sdk_4.15.0/frameworks/libs/player/22.0/
  - export FLEX_HOME="$TRAVIS_BUILD_DIR/flex_sdk_4.15.0"

script:
  - ant
